import { type Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";
import { Theme } from "@/theme/provider";

export const metadata: Metadata = {
  title: "What I Can Do",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <TRPCReactProvider>
          <Theme>{children}</Theme>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
